### ISSUE TITLE
OTR fragmentation support

### ISSUE THREAD

**Issue by mmb** [ibauersachs/otr4j#11]
Are there any plans to support receiving fragmented OTR messages?

It would fix compatibility between ChatSecure for Android and clients that send messages over IRC like bitlbee.

**Comment by gpolitis** [comment]
This is a much wanted feature but I'm afraid I don't currently have the time to implement it, I'm sorry. Pull requests are very welcome of course :)

**Comment by gpolitis** [comment]
If you (or someone else) want(s) to implement this feature, it's best to work on the otrV3 branch that adds support for OTRv3 (see #4) and will be merged into master soonish.

**Comment by gpolitis** [comment]
Pull request #12 (merged into branch otrV3) fixes this issue. I'll merge the otrV3 branch into master; increase the otr4j version and update the maven repository.
