### ISSUE TITLE
Remove OTRv1

### ISSUE THREAD

**Issue by DrWhax** [ibauersachs/otr4j#25]
I think it's about time we start removing OTRv1 from the OTR ecosystem of reference libraries, as well as in libotr. We've been working towards this on libotr and Ian said, please go ahead and start removing OTRv1 from libotr.

It's a security issue if a protocol degrade can happen for whatever reason and I don't think there is any justification anymore for "backwards compatibility".

Thanks for your consideration!

**Comment by cobratbq** [comment]
FWIW, I agree and would like to see this happen.

**Comment by cobratbq** [comment]
I checked this in the code. We only have very minimal "support" for OTRv1, simply to recognize some of the protocol aspects, such as the whitespace tags. Any relevant operation (such as starting AKE) which involves OTRv1 is unsupported. Effectively, OTRv1 is not supported by otr4j.
