### ISSUE TITLE
OTRv4? v3? Hmm.

### ISSUE THREAD

**Issue by n8fr8** [ibauersachs/otr4j#4]
Nathan from Guardian here... we have users starting to request OTRv4 support:

https://twitter.com/Dymaxion/status/276050214878576641

 but they may mean "libotr4" which is OTRv3

Any thoughts on how far we are from parity with the latest update of libotr that with otr4j?

**Comment by gpolitis** [comment]
It's on the todo list, but I'm not sure when it will be done. I was hoping to find some spare time during the holidays to dig a little deeper into this, but that unfortunately that didn't happen.

**Comment by devrandom** [comment]
I started on the TLV 8 (extra symmetric key) part of OTRv3 support for otr4j.  I have a draft of the API here:

https://github.com/devrandom/Gibberbot/commit/f4635c28cc2ddefc9eefce359c6cdf3f8bdd7a68

Any ideas about way to better structure the API?  In particular, I wonder if there is a better way to get out the extra data without passing in a list.

**Comment by devrandom** [comment]
I've upgraded the API and wrote a draft implementation of the input side:

https://github.com/guardianproject/Gibberbot/pull/191

**Comment by gpolitis** [comment]
The otrV3 branch (adds V3 and fragmentation support) has been merged into master.
