### ISSUE TITLE
Whitespace parsing is backwards

### ISSUE THREAD

**Issue by devrandom** [ibauersachs/otr4j#6]
Right now the regexp has v1 and v2 whitespace patterns backwards.

This causes the following:
- If the peer advertises v1,v2, this is parsed as v2 only
- If the peer advertises v2,v3, this is parsed as v1 only

The latter eventually causes an UnsupportedOperationException.  This happens, for example, with the latest Pidgin and can cause messages to be silently dropped.

ChatSecure (was Gibberbot) fix here: https://github.com/guardianproject/ChatSecureAndroid/pull/336/files

(sorry, we still have otr4j in-tree - will extract soon)

**Comment by gpolitis** [comment]
Fixed. Thank you devrandom.
